import streamlit as st

st.image("images_and_videos/home1.jpg")
st.markdown("**Citation**  \n**Adeosun SO.** *AuthormetriX: Automated Calculation of Individual Authors’ Non-Inflationary Credit-Allocation Schemas’ and Collaboration Metrics from a Scopus Corpus.* **bioRxiv** 2025.01.19.633820; doi: https://doi.org/10.1101/2025.01.19.633820")
#st.markdown("**About**  \nAuthormetriX use, function and features are described in detail in the citation above.  \nThe main feature of AuthormetriX calculates individual authors' scholarly output based on 15 different author credit allocation schemas. It also provides collaboration metrics.  \nClick the '>' button on the top left corner of this page to reveal the navigation bar containing the tabs to the other pages and functions of AuthormetriX.  \nReview the How-to videos below to learn how to obtain the required input information from Scopus.com.")
st.markdown("**About**")
st.write("""
         - AuthormetriX' use, functions, and features are described in details in the citation above.
         - The main feature of AuthormetriX calculates individual authors' scholarly output based on 15 different author credit allocation schemas. It also provides collaboration metrics.
         - Click the '>' button on the top left corner of this page to unhide the navigation sidebar containing the tabs to the other pages and functions of AuthormetriX.
         - Review the How-to videos below to learn how to obtain the required input information from Scopus.com.
         """,unsafe_allow_html=True)

st.markdown("**Update notes**")
st.write("""
         - [02/18/2026] A new schema, "harmonic with last author bump" (harmonic_LAB) added to the main calculator and both modelers.
         """,unsafe_allow_html=True)

st.markdown("### How-to Videos")
st.markdown("""<hr style="height:4px;border:none;color:#fe8100;background-color:#fe8100;" />""", unsafe_allow_html=True)

st.markdown("##### 1. Getting authors' Scopus IDs")
st.video('images_and_videos/Guide_1.mp4')

st.markdown("""<hr style="height:4px;border:none;color:#fe8100;background-color:#fe8100;" />""", unsafe_allow_html=True)

st.markdown("##### 2. Getting the relevant corpus with authors' Scopus IDs")
st.video('images_and_videos/Guide_2.mp4')

st.markdown("""<hr style="height:4px;border:none;color:#fe8100;background-color:#fe8100;" />""", unsafe_allow_html=True)


st.markdown ("Thank you for using ***AuthormetriX***.  *Kindly remember to cite the publication (full citation above).*",unsafe_allow_html=True)
st.markdown ("*Header generated by font-generator.com*")  
